version: "3"

services:
  nodeapp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - dev-network
    container_name: app
    environment:
      - PORT=80
      - ENV="DEV"
      - TOKEN="hwe6b3uEdpO6DuiytJXNfg"
  
  database:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=address-book
      - MONGO_INITDB_ROOT_USERNAME=autobooks
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./volumes/mongodb:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - dev-network
  
  logging:
    image: 'datalust/seq'
    container_name: dev-seq
    volumes:
      - ./volumes/seq:/data
    ports:
      - 80:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
    networks:
      - dev-network

networks:
  dev-network: